[package]
name = "pari"
version = "0.1.0"
authors = ["Borodin Gregory <grihabor@yandex-team.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54.0"